import React, { useState, useEffect, useMemo } from 'react';
import { getLocalPosts, getLocalPrompts, type LocalPost, type LocalPrompt } from '../lib/storage';
export function EngagementCharts() {
  const [posts, setPosts] = useState<LocalPost[]>([]); const [prompts, setPrompts] = useState<LocalPrompt[]>([]); const [view, setView] = useState<'time'|'prompts'|'tones'>('time');
  useEffect(()=>{getLocalPosts().then(setPosts);getLocalPrompts().then(setPrompts);},[]);
  const timeData = useMemo(()=>{const h:Record<number,{t:number;c:number}>={};for(let i=0;i<24;i++)h[i]={t:0,c:0};posts.forEach(p=>{const hr=new Date(p.postedAt).getHours();h[hr].t+=p.likes+p.retweets*2+p.replies*3;h[hr].c++;});return Object.entries(h).map(([hr,d])=>({hour:+hr,label:`${hr}:00`,avg:d.c>0?d.t/d.c:0,count:d.c}));},[posts]);
  const promptData = useMemo(()=>prompts.filter(p=>p.useCount>0).sort((a,b)=>b.avgEngagement-a.avgEngagement).slice(0,10),[prompts]);
  const toneData = useMemo(()=>{const t:Record<string,{t:number;c:number}>={};posts.forEach(p=>{if(!t[p.tone])t[p.tone]={t:0,c:0};t[p.tone].t+=p.likes+p.retweets*2+p.replies*3;t[p.tone].c++;});return Object.entries(t).map(([tone,d])=>({tone,avg:d.c>0?d.t/d.c:0,count:d.c}));},[posts]);
  const mx=(a:number[])=>Math.max(...a,1);
  return (<div className="space-y-4">
    <div className="flex gap-1 bg-[#0d1117] rounded-lg p-1">{(['time','prompts','tones'] as const).map(v=>(<button key={v} onClick={()=>setView(v)} className={`flex-1 py-1.5 rounded text-xs font-medium ${view===v?'bg-[#1d9bf0] text-white':'text-[#71767b]'}`}>{v==='time'?'⏰ Time':v==='prompts'?'📝 Prompts':'🎭 Tones'}</button>))}</div>
    {view==='time'&&<div><h4 className="text-sm font-medium mb-2">Best Times</h4>{posts.length===0?<p className="text-[#71767b] text-xs text-center py-4">Post replies first</p>:<div className="flex items-end gap-0.5 h-32">{timeData.map(d=>(<div key={d.hour} className="flex-1 flex flex-col items-center justify-end h-full group relative"><div className="absolute -top-6 bg-[#15202b] text-xs px-1 py-0.5 rounded opacity-0 group-hover:opacity-100 whitespace-nowrap z-10">{d.label}: {d.avg.toFixed(1)} ({d.count})</div><div className="w-full rounded-t bg-[#1d9bf0]/60 hover:bg-[#1d9bf0]" style={{height:`${Math.max((d.avg/mx(timeData.map(t=>t.avg)))*100,2)}%`}}/>{d.hour%6===0&&<span className="text-[10px] text-[#71767b] mt-1">{d.label}</span>}</div>))}</div>}</div>}
    {view==='prompts'&&<div><h4 className="text-sm font-medium mb-2">Rankings</h4>{promptData.length===0?<p className="text-[#71767b] text-xs text-center py-4">Use prompts first</p>:promptData.map((p,i)=>(<div key={p.id} className="flex items-center gap-2 mb-2"><span className="text-xs text-[#71767b] w-4">#{i+1}</span><div className="flex-1"><div className="text-xs truncate mb-0.5">{p.text}</div><div className="h-2 bg-[#0d1117] rounded-full overflow-hidden"><div className="h-full bg-[#1d9bf0] rounded-full" style={{width:`${(p.avgEngagement/mx(promptData.map(d=>d.avgEngagement)))*100}%`}}/></div></div><span className="text-xs text-[#71767b]">{p.avgEngagement.toFixed(1)} ({p.useCount})</span></div>))}</div>}
    {view==='tones'&&<div><h4 className="text-sm font-medium mb-2">Tones</h4>{toneData.length===0?<p className="text-[#71767b] text-xs text-center py-4">Post replies first</p>:toneData.map(d=>(<div key={d.tone} className="mb-3"><div className="flex justify-between text-xs mb-1"><span>{d.tone}</span><span className="text-[#71767b]">{d.avg.toFixed(1)} ({d.count})</span></div><div className="h-3 bg-[#0d1117] rounded-full overflow-hidden"><div className="h-full bg-[#1d9bf0] rounded-full" style={{width:`${(d.avg/mx(toneData.map(t=>t.avg)))*100}%`}}/></div></div>))}</div>}
  </div>);
}
